### PR TITLE
Tiny issue fixes (#608 #712)

### LINKED ISSUE #608: withdraw to not show correctly
image
there will be some overlap

### PR DESCRIPTION
**Pull request by ippudo**
This is to fix #608 and #712.

712 The transaction table can now being collapsed.

608 The address column at withdraw table are now wrapped for shorten the table rows.

### CODE REVIEW

**Comment by dwalintukan** [comment]
Also, Alex suggested to use a standalone component that keeps track of the `expanded` boolean like this: https://github.com/bodhiproject/bodhi-ui/pull/724/files#diff-826e6f49ed1985f1a821cb65dc169991R10

File: src/scenes/Event/components/EventTxHistory/index.js [hunk 1]
```diff
@@ -76,31 +83,33 @@ export default class EventTxHistory extends Component {
   }
 
   renderTxRow = (transaction) => {
-    const { intl } = this.props;
+    const { intl, classes } = this.props;
     const { locale, messages: localeMessages } = intl;
+    const isExpanded = this.state.expanded.includes(transaction.txid);
 
     const result = [];
     result[0] = (
```
Comment (alex-cory) [inline src/scenes/Event/components/EventTxHistory/index.js]: ok, so here's a lesson in `<Fragment>`s and managing state for a list of items. Let's do this instead
```js
@withStyles(styles)
class TxRow extends Component {
  state = {
    expanded: false
  }

  toggle = () => this.setState({ expanded: !this.state.expanded })

  render() {
    const { transaction, classes, intl: { locale, localeMessages } } = this.props
    const { txid, createdTime, amount, token, type, status } = transaction
    const { expanded } = this.state

    return (
      <Fragment>
        <TableRow key={txid} onClick={this.toggle}>
          <TableCell padding="dense">{getShortLocalDateTimeString(createdTime)}</TableCell>
          <TableCell padding="dense">{getTxTypeString(type, locale, localeMessages)}</TableCell>
          <TableCell padding="dense">{description}</TableCell>
          <TableCell padding="dense">
            {!amount ? '' : `${amount} ${token}`}
          </TableCell>
          <TableCell padding="dense">{transaction.status}</TableCell>
          <TableCell padding="dense"><i className={cx(expanded ? 'icon-ic_down' : 'icon-ic_up', 'icon iconfont', classes.arrowSize)} /></TableCell>
        </TableRow>
        {expanded && (
          <Fragment>
            <TableRow selected onClick={this.toggle} key={`txaddr-${txid}`}>
              <TransactionHistoryID transaction={transaction} />
              <TableCell /><TableCell /><TableCell /><TableCell /><TableCell />
            </TableRow>
            <TableRow selected onClick={this.toggle} key={`txaddr-${txid}`}>
              <TransactionHistoryAddress transaction={props} />
              <TableCell /><TableCell /><TableCell /><TableCell /><TableCell />
            </TableRow>
          </Fragment>
        )}
      </Fragment>
    );
  }
}

```
and then in the render method
```
render() {
  return (
    ...
    <TableBody>
      {transactions.map((transaction, index) => (
        <TxRow {...transaction} description={this.getDescription(transaction)} key={transaction.txid} />
      ))}
    </TableBody>
    ...
  )
}
```

Comment (alex-cory) [reply src/scenes/Event/components/EventTxHistory/index.js]: we can cleanup the `getDescription` method later

File: src/scenes/Event/components/EventTxHistory/index.js [hunk 2]
```diff
@@ -12,13 +11,8 @@ import {
   withStyles,
 } from '@material-ui/core';
 
+import TxRow from './txRow';
```
Comment (alex-cory) [inline src/scenes/Event/components/EventTxHistory/index.js]: please name `./txRow` as PascalCase like `./TxRow`. To stay consistent with most of our app, let's make it this way please :)

File: src/scenes/Event/components/EventTxHistory/txRow.js [hunk 3]
```diff
@@ -0,0 +1,92 @@
...
+    expanded: false,
+  }
+
+  toggle = () => {
+    // probably need some logic here for not expanding when clicking on
+    // the Name link field
+    this.setState({ expanded: !this.state.expanded });
+  };
+
+  getDescription = (tx) => {
```
Comment (alex-cory) [inline src/scenes/Event/components/EventTxHistory/txRow.js]: let's make this a js `getter` like this
```js
get name() {
  const { optionIdx, topic, type, intl } = this.props
  // then we don't have to us "tx.whatever" everywhere
}
```
then we can use it below like
```js
<TableCell padding="dense">{this.name}</TableCell>
// instead of
<TableCell padding="dense">{this.getDescription(transaction)}</TableCell>
```

File: src/scenes/Event/components/EventTxHistory/index.js [hunk 4]
```diff
@@ -58,11 +51,13 @@ export default class EventTxHistory extends Component {
...
                 </TableCell>
+                <TableCell padding="dense">
+                </TableCell>
               </TableRow>
             </TableHead>
             <TableBody>
-              {_.map(transactions, (transaction, index) => (
-                this.renderTxRow(transaction, index)
+              {transactions.map((transaction) => (
+                <TxRow key={transaction.txid} transaction={transaction} intl={intl} />
```
Comment (alex-cory) [inline src/scenes/Event/components/EventTxHistory/index.js]: 1. we don't need to pass `intl` here if we're using `@injectIntl` on our `TxRow` component
2. let's spread `transaction` here like `{...transaction}`

File: src/scenes/Event/components/EventTxHistory/txRow.js [hunk 5]
```diff
@@ -0,0 +1,92 @@
+import React, { Component, Fragment } from 'react';
+import PropTypes from 'prop-types';
+import { injectIntl, intlShape } from 'react-intl';
+import {
```
Comment (alex-cory) [inline src/scenes/Event/components/EventTxHistory/txRow.js]: let's make this 1 line please
