### PR TITLE
update codes with Harrison for the new block transactions bugs

### LINKED ISSUE #866: Appolo error at console while block number updated
appolo

This bugs doesn't related to removing redux.

### PR DESCRIPTION
**Pull request by amazingandyyy**
fix #866

### CODE REVIEW

File: src/scenes/Event/store.js [hunk 1]
```diff
@@ -131,6 +131,7 @@ export default class EventStore {
   @action
   initTopic = async () => {
     // GraphQL calls
+    this.app.ui.location = Routes.TOPIC;
```
Comment (ippudo) [inline src/scenes/Event/store.js]: Editing this will leads backbutton boom. Need other solution.
