### PR TITLE
788 wrong qtum amount validation for BET and WITHDRAWDIALOG

### LINKED ISSUE #790: Should remove the `token amount not enough` warning when changing wallet [Oracle]
In oracle detail page, once detect token amount not enough, and then change wallet address, need to enter a number to remove the `token amount not enough` warning

### PR DESCRIPTION
**Pull request by ippudo**
NOTE: **NOT FULLY TESTED**. Need more people to try.

#788 , both BET in the topic and WITHDRAWDIALOG in the followup.
Part of #789 since CREATEEVENT also use wrong amount of QTUM, but I'm feeling problems at 789 is more than this.

Possibly fixed #790 but not able to test

### CODE REVIEW

File: src/scenes/Event/store.js [hunk 1]
```diff
@@ -383,8 +383,8 @@ export default class EventStore {
     const { phase, resultSetterQAddress, resultSetStartTime, isOpenResultSetting, consensusThreshold } = this.oracle;
     const { global: { syncBlockTime }, wallet } = this.app;
     const currBlockTime = moment.unix(syncBlockTime);
-    const totalQtum = _.sumBy(wallet.addresses, ({ qtum }) => qtum);
-    const notEnoughQtum = totalQtum < maxTransactionFee;
+    const currentWalletQtum = wallet.lastUsedWallet.qtum;
```
Comment (amazingandyyy) [inline src/scenes/Event/store.js]: `wallet.lastUsedWallet` looks cool
